### ISSUE TITLE
Please bump peer dependencies in your lib ngx-pass-code to v17

### ISSUE THREAD

**Issue by bobbhy** [dineeek/ngx-libs-workspace#15]
Hi @dineeek 

I hope you're doing well! I'm using your library, ngx-pass-code, in my Angular side project, and I noticed that the peer dependencies for @angular/common and @angular/core haven't been updated to version 17.3.10 in the latest release.

Here's the link for reference:
https://github.com/dineeek/ngx-libs-workspace/blob/main/libs/ngx-pass-code/package.json

Would it be possible for you to bump these versions and publish a new version (1.1.3) when you get a chance? Thank you so much in advance!

**Comment by dineeek** [comment]
Hello @bobbhy,

thanks for using this library. I did some migrations on repo but left a publishing to do it later. Thanks for reminder :)

New version has been published **ngx-pass-code@1.2.0**.

Thanks again!
